version: '2.0'
services:
  cassandra:
    image: cassandra
    ports:
    - "9042:9042"
    volumes:
    - cassandra:/var/lib/cassandra

  cassandra_web: # changer  dossier 
    depends_on:
      - cassandra
    image: delermando/docker-cassandra-web:v0.4.0 
    #image: cassandraproject/web
    ports:
    - "3000:3000"
    environment:
      CASSANDRA_HOST_IP: "127.0.0.1"
      CASSANDRA_PORT: "9042"
      CASSANDRA_USER: "cassandra" 
      CASSANDRA_PASSWORD: "cassandra"
    
  python: # changer map  dossier compiler mettre le docker file ./
    build: . # charge en local un csv + envoi a cassandra 
    volumes:
    - python:/data/
    depends_on:
      - cassandra

volumes:
   cassandra: {}
   python: {}
