version: '2.0'
services:
  cassandra:
    image: cassandra
    ports:
    - "9042:9042"
    volumes:
    - cassandra:/var/lib/cassandra
    container_name: "cassandra_v3"
    

  cassandra_web:
    restart: always
    links:
      - cassandra
    image: delermando/docker-cassandra-web:v0.4.0 
    env_file:
      - .env
    ports:
    - "3000:3000"
    environment:
      CASSANDRA_HOST_IP: "${host_ip}"
      CASSANDRA_PORT: "9042"
      CASSANDRA_USER: "cassandra" 
      CASSANDRA_PASSWORD: "cassandra"
    container_name: "cassandra-web_v3"
  python: 
    restart: always
    build: . 
    volumes:
    - python:/data/
    links:
      - cassandra

volumes:
   cassandra: {}
   python: {}
